---

- hosts: database7
  become: yes

  tasks:
  - name: add MariaDB yum repo
    template:
      src: /ansible/database/MariaDbRepo.j2
      dest: /etc/yum.repos.d/MariaDB.repo

  - name: install MariaDB-server 
    yum:
      name: MariaDB-server

  - name: start and enable MariaDB
    service:
      name: mariadb
      enabled: yes
      state: started
